### ISSUE TITLE
Using "http_compress" in opensearch-py causing opensearchpy.exceptions.AuthenticationException for cluster settings

### ISSUE THREAD

**Issue by ns-se-ops** [awsdocs/amazon-opensearch-service-developer-guide#69]
Provided code is working on indices with `http_compress` : https://github.com/awsdocs/amazon-opensearch-service-developer-guide/blob/master/doc_source/gzip.md#sample-code-python-3

The same would result in below error for cluster settings
```
import boto3
from requests_aws4auth import AWS4Auth
from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth

host = '' # cluster endpoint, for example: my-test-domain.us-east-1.es.amazonaws.com
region = '' # e.g. us-west-1

credentials = boto3.Session().get_credentials()
auth = AWSV4SignerAuth(credentials, region)

client = OpenSearch(
    hosts = [{'host': host, 'port': 443}],
    http_auth = auth,
    use_ssl = True,
    http_compress=True,
    verify_certs = True,
    connection_class = RequestsHttpConnection
)


# document = {
# "title": "Moneyball",
#  "director": "Bennett Miller",
#  "year": "2011"
# }

# Send the request.
# print(client.index(index='movies', id='1', body=document, refresh=True))

res = client.cluster.put_settings({"persistent": {"cluster.max_shards_per_node": 1500}})
print(f'Set result: {res}')
```

Output:
```
Traceback (most recent call last):
  File "/Users/xxxx/s3-to-opensearch/OSClientModified.py", line 22, in <module>
    res = client.cluster.put_settings({"persistent": {"cluster.max_shards_per_node": 1500}})
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/client/cluster.py", line 229, in put_settings
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py", line 407, in perform_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/transport.py", line 368, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/connection/http_requests.py", line 203, in perform_request
    self._raise_error(
  File "/usr/local/lib/python3.9/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.AuthenticationException: AuthenticationException(401, '{"Message":"Your request: \'/_cluster/settings\' payload is not allowed."}')
```

The same request will work by remove "http_compress" from client
```
client = OpenSearch(
    hosts = [{'host': host, 'port': 443}],
    http_auth = auth,
    use_ssl = True,
    verify_certs = True,
    connection_class = RequestsHttpConnection
)
```

**Comment by dblock** [comment]
I know this is a bit old, but would you care to check whether the docs in https://github.com/opensearch-project/opensearch-py are correct. We plan to simplify the documentation here and really point to that project's samples and documentation that can be unit-tested and such.
