### ISSUE TITLE
Serverless Python sample is not working

### ISSUE THREAD

**Issue by dblock** [awsdocs/amazon-opensearch-service-developer-guide#88]
Running sample from https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-clients.html#serverless-python as is, getting an error server-side.

```
Creating index:
{'status': 500, 'request-id': 'd64063a6-f54e-959e-81e7-764d8ee886eb', 'error': {'reason': 'There was a server error. Please try again or contact AWS Support', 'type': 'InternalFailure'}}
Traceback (most recent call last):
  File "/Users/dblock/source/dblock/opensearch-python-client-demo/foo.py", line 50, in <module>
    client.index(index=index_name, body=document, id='1')
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/client/utils.py", line 178, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/client/__init__.py", line 355, in index
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/transport.py", line 408, in perform_request
    raise e
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/transport.py", line 369, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/connection/http_requests.py", line 210, in perform_request
    self._raise_error(
  File "/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/connection/base.py", line 301, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.TransportError: TransportError(500, 'InternalFailure')
```

**Comment by dblock** [comment]
This was something transient, closing.
