### ISSUE TITLE
Not able to run the sample code in Java 8. getting UnsupportedClassVersionError:

### ISSUE THREAD

**Issue by rajavijaysingh** [awsdocs/amazon-opensearch-service-developer-guide#94]
I am trying to run the sample code on Java 8 getting the unsupported class version error. Seems like the libraries are all built on Java 11 and are not able to be reference from Java 8. below is the error I am trying to run the GetVersion.java on jre1.8.0_40. 

`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/opensearch/client/transport/OpenSearchTransport has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
`

**Comment by lizsnyder** [comment]
@rajavijaysingh you have not provided a link to the documentation you're referring to.

**Comment by dblock** [comment]
If you mean the Sigv4 interceptor code, the community maintained version in https://github.com/acm19/aws-request-signing-apache-interceptor supports JDK8.
